apiVersion: v1
kind: Service
metadata:
  name: hello-laravel
  labels:
    app: hello-laravel
    team: SRE
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    name: http
  selector:
    app: hello-laravel